### ISSUE TITLE
Dynamic cell size breaks dragging

### ISSUE THREAD

**Issue by danielchristopher1** [mmick66/KDDragAndDropCollectionView#14] opened 2017-01-27 10:29 UTC
I configured my collection view cells to calculate their height by overriding `UICollectionViewCell.preferredLayoutAttributesFitting`.

When I do this, dragging appears to break in a weird way. When I first drag an item from one collection view to another, the items in the collection view I'm dragging to all move down to make room for the cell I'm dragging, even though the cell I'm dragging barely even entered the other collection view. After about a second, the cells in the collection view I'm dragging to all re-arrange and go back to normal. At that point, I can drag the new cell into it's position.

Any ideas on what this may be? I've spent the last two days trying to figure it out...

It seems to be something in the `KDDragAndDropCollectionView.didMoveItem` function.

Thanks.

**Comment by mmick66** [comment] 2017-01-30 08:39
Please send me a zip of your project here because it is hard to understand what you are trying to do....

**Comment by georgbachmann** [comment] 2017-02-06 09:23
Any update on that one?
I am having most likely the same problem here.
So when you enable dynamic-cell sizing (simple set an estimated cell size on the layout) dragging a cell will result in very strange animations

**Comment by mmick66** [comment] 2017-02-06 09:25
Can someone send me a zip with their project so I can have a look?

**Comment by georgbachmann** [comment] 2017-02-06 09:31
Sure... so the only changes I did from you code:
Create and outlet for one `UICollectionViewFlowLayout`, give it an estimated item size (ViewController:41).

That's it...

So now the items will be the exact size they need to be, but now when dragging any item in the top collecitonview will result in strange animations

Thanks for having a look!

[KDDragAndDropCollectionView-master-2.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/754139/KDDragAndDropCollectionView-master-2.zip)

**Comment by mmick66** [comment] 2017-02-08 11:11
I see that you are using:

`flowLayoutOfFirstCollectionView.estimatedItemSize = CGSize(width: 100, height: 100)`

I have never used that method so I cannot know how it is best to implement, but it is definitely causing a problem... Have a look at the zip below where I implemented the 100x100 size which you suggest, directly in the Storyboard.


[KDDragAndDropCollectionView-simple-change-size.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/760433/KDDragAndDropCollectionView-simple-change-size.zip)

**Comment by mmick66** [comment] 2017-02-08 11:26
Yet another way is to implement:

```
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
    if collectionView.tag == 0 {
        return CGSize(width: 40, height: 80)
    } else {
        return CGSize(width: 69, height: 127)
    }
}
```

This way you can have dynamic cell sizes. I am still using the tag which is probably bad practice, but consider it a method of convenience which can be replaced. Please see the full project attached.

[KDDragAndDropCollectionView-dynamic-cell-size.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/760461/KDDragAndDropCollectionView-dynamic-cell-size.zip)

**Comment by georgbachmann** [comment] 2017-02-08 11:29
Awesome, thank you for having a look!
I'd like to not implement `sizeForItem` as the CollectionView would do that herself... So just having correct layout-constraints would then be enough, but I need the `estimatedItemSize` in order for that to work.
So my 100x100 ist just there to make the CollectionView figure out the correct size itself
I guess the problem is somewhere in a AnimationBlock that you are doing or so. Didn't have time yet to have a closer look

**Comment by mmick66** [comment] 2017-02-08 11:33
Why do you need the `estimatedItemSize` ?

Reading Apple's docs, it seems to be only an optimisation!

_Providing an estimated cell size can improve the performance of the collection view when the cells adjust their size dynamically. Specifying an estimate value lets the collection view defer some of the calculations needed to determine the actual size of its content. Specifically, cells that are not onscreen are assumed to be the estimated height._ (source: [Apple](https://developer.apple.com/reference/uikit/uicollectionviewflowlayout/1617709-estimateditemsize))

It is also logging some warnings about the snapshot being taken before the view is rendered which I suspect is due to that method.

**Comment by georgbachmann** [comment] 2017-02-08 12:09
If you set it, the collectionview will do the calculation of the cells required bounds for you. You wouldn't need to do anything extra if you have cells that size depending on their content.

**Comment by mmick66** [comment] 2017-02-08 13:28
I am looking at your code and I do not see any calculations. All I see is this single line of code that says:
`flowLayoutOfFirstCollectionView.estimatedItemSize = CGSize(width: 100, height: 100)`

The cells are **all** small and their size does not seem to depend on their content. 

Even if this was the case however, the method:
`
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize`

should do the job rather than the one you use... I am going to close this issue but feel free to continue this discussion if you think that your problem is not addressed fully.

**Closed as completed by mmick66** 2017-02-08 13:28 UTC

**Comment by georgbachmann** [comment] 2017-02-08 13:50
See f.e. https://stackoverflow.com/questions/25895311/uicollectionview-self-sizing-cells-with-auto-layout/25896386#25896386
If you enable dynamic-cell sizing (by giving an `estimatedItemSize`), iOS will make every cell fit it's content. In your sample, they are all small, because the content they hold is just two lines of text.
This is a very useful feature of UICollectionView (UITableView also has this feature) if your cells aren't all the same size but change depending on their content.
I guess this is quite common that people use that feature, so it would be super-duper-awesome if your library could support that
I hope I have time soon to have a closer look myself

**Comment by mmick66** [comment] 2017-02-08 14:00
Well, first of all, the stackoverflow link you sent me explains a number of steps to do what you want and you seem to have implemented only the first.

Secondly, instead of going in that way, why not do something simple by calculating the size and setting it manually in the delegate method that I copied above?

I actually wrote a blog post on how to do this so you might want to have a look...

http://blog.karmadust.com/category/ios/page/4/

**Comment by georgbachmann** [comment] 2017-02-08 14:07
Sure I could do that, but why do something iOS does automatically for you?
When looking at the StackOverflow post... It states:
1. Set estimatedItemSize
2. Add support for sizing on your cell subclass. This comes in 2 flavours; Auto-Layout or custom override of preferredLayoutAttributesFittingAttributes.

So by simply having a cell with proper autolayout-constraints and the `estimatedItemSize`, everything is already done. So in your sample, simply adding `estimatedItemSize` was enough to get auto-sizing to work. The small cells are the prove that it is doing what it should... every cell is the size it needs to be, perfekt!

Sure, I know I can do it manually by implementing `sizeForItem`, but when having very large datasets with quite complex cells (layout wise) that's not what you want to do upfront. So by having an estimate, the CollectionView will calculate the actual size only when it really needs it (when the cell is displayed).
That will make the difference between a CollectionView that loads fast, and one that loads slow if you have large datasets.

**Comment by mmick66** [comment] 2017-02-08 14:19
Ok, this `estimatedItemSize` is _relatively_ new (iOS 8+). We could do the same just fine before. You would not miss it if it was not there in other words.

Most importantly... You have not implemented `preferredLayoutAttributesFitting`. At least not in the zip you have given me... so how can it work???

**Comment by georgbachmann** [comment] 2017-02-08 14:45
That's cause it's Auto-Layout __or__ custom override of preferredLayoutAttributesFittingAttributes
So you don't actually need the override of preferredLayoutAttributesFittingAttributes

See: https://developer.apple.com/reference/appkit/nscollectionviewelement/1528259-preferredlayoutattributesfitting and https://developer.apple.com/reference/appkit/nscollectionviewflowlayout/1402896-estimateditemsize

Also, I would miss `estimatedItemSize` a LOT :) cause it helps calculating an items size just when you need it, not before... that's a HUGE benefit
And also it also makes me having to write far less code :)

**Comment by mmick66** [comment] 2017-02-08 14:54
Ok, then `estimatedItemSize` might not work with dragging and dropping, what can I say. At least we can still do it manually.
