### ISSUE TITLE
image of cell getting stuck occasionally 

### ISSUE THREAD

**Issue by neilsekhon** [mmick66/KDDragAndDropCollectionView#9] opened 2016-04-17 21:16 UTC
Sometimes the image of the cell gets stuck in the collection view and will only go away when the app is restarted.

Thanks, Neil

**Comment by mmick66** [comment] 2016-04-18 07:05
Can you reproduce? What are the steps?

**Comment by neilsekhon** [comment] 2016-04-19 01:13
It happens rarely, but when I drag the cell from my bottom collection view to the top collection view (where cells are arranged in one vertical column), the cell (or image of cell) will become stuck in the collection view even when the data is reloaded.

**Comment by mmick66** [comment] 2016-04-19 07:55
What do you mean by "where cells are arranged in one vertical column"? All the columns are arranged horizontally... 
![rows](https://cloud.githubusercontent.com/assets/342781/14631667/db1a6976-0614-11e6-95e1-c719a995eea2.png)

**Comment by neilsekhon** [comment] 2016-04-19 18:47
In my app the flow layout is vertical instead of horizontal

**Comment by mmick66** [comment] 2016-04-20 07:11
I see, well, if you think I could reproduce it somehow you can send me your app (drop it here) and I could have a look for you. Otherwise I must close this issue as I cannot reproduce it.

**Closed as completed** 2016-04-24 10:53 UTC
